name: Coverage
on: push
jobs:
  coverage:
    name: Coverage
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-nox.yaml@main
    with:
      python-version: '3.10'
      architecture: x64
      sessions: tests-3.10
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
