# .github/workflows/release.yml
name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: python3 -m pip install --user pipx
    - run: python3 -m pipx ensurepath
    - run: pipx install nox==2020.8.22
    - run: pipx install poetry==1.1.4
    - run: pipx inject nox nox-poetry
    - run: nox
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
